# Generated by Django 2.0.6 on 2018-06-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CallApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
