# Generated by Django 2.0.6 on 2018-06-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CallApi', '0006_auto_20180611_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=100)),
                ('call_identifier', models.DateTimeField()),
                ('origin_phone_number', models.IntegerField()),
                ('destination_phone_number', models.IntegerField()),
                ('record_timestamp', models.DateTimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
